#
# --/연동 설정/--
# 채팅, 후원을 연동합니다
# 연동을 원치 않다면 false로 설정하세요
#
채팅: true
후원: true

#
# --/메세지/--
# format: 채팅,후원시 츨력되는 메세지 입니다.
# tformat: 채팅,후원시 츨력되는 타이틀 입니다(타이틀을 출력하고 싶지 않다면 공백).
# !-- 채팅은 앞에 유저가 설정한 채널 명이 "[ (채널명) ] format" 처럼 맨 앞에 들어갑니다.--!
#

# {user}: 닉네임
# {msg}: 메세지
# {paid}: 후원 금액
# {plat} 플렛폼
# --/채팅/--
chat:
  format: "&f {user} : {msg} &7- &r&l[ {plat} ]"
# --/후원/--
donation:
  format: "&e{paid}원 &7>&f{user} &d:: &b{msg} &7- &r&l&6[ 후원 ]"
  view-title: true
  tformat: "&e{paid}&f원 후원!"

# --/플렛폼 표시 설정/--
# color가 true일때 {plat}이 치지직이라면 "치지직"이라는 글자가 초록색으로 표기됩니다.
color: true
# 치직일 경우 Chzzk으로 표시됨
en: false

# --/아프리카후원 설정/--
# 아프리카 후원금액 표시 설정입니다
# true일 시 후원 금액이 별풍성 개수로 표시 됍니다.
BoolOrPay: true

#
# --/후원 이벤트/--
# 후원을 받았을때 그 금액에 설정된 명령어를 실행합니다
# 명령어를 실행하고 싶지 않다면 공백으로 두거나 아예 지워버리면 됩니다.
# 콘솔에서 실행-> 앞에 $ 붙이기
# ex) 10000: "kill {player}" -> 1000원을 후원 받으면 kill 명령어가 실행됨
# {player}::플레이어 닉네임
# {msg} :: 후원 메세지
# {paid} :: 후원 금액
# !- 명령어의 주제는 채널의 주인( 채널을 등록한 플레이어 )입니다 -!
#
donation-event:
#  '1000': "kill {player}"
#  '2000': "say a"