name: withStream
version: ${version}
main: kr.apo2073.stream.Stream
api-version: '1.13'
authors: [ 아포칼립스 ]
commands:
  후원:
    description: 후원 이벤트 명령어 설정 기본 명령어
  치지직:
    description: 치지직 채널 등록 기본 명령어
  투네이션:
      description: 투네이션 채널 등록 기본 명령어
  아프리카:
    description: 아프리카 채널 등록 기본 명령어
  유튜브:
    description: 유튜브 채널 등록 기본 명령어
  리로드:
    description: 플러그인 config 리로드 명령어
  strm:
    description: withStream 관리자 명령어

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0
  - com.squareup.okhttp3:okhttp:4.9.3
  - org.java-websocket:Java-WebSocket:1.5.2
  - com.google.apis:google-api-services-youtube:v3-rev20230816-2.0.0
  - com.google.http-client:google-http-client-jackson2:1.39.2
  - com.google.api-client:google-api-client:1.33.0
  - net.kyori:adventure-text-minimessage:4.17.0
  - net.kyori:adventure-platform-bukkit:4.3.4
  - net.kyori:adventure-text-serializer-plain:4.17.0

permissions:
  stream.*:
    children:
      stream.channel: true
      stream.reload: true
      stream.donation: true
      stream.admin: true

    stream.channel:
      default: true
    stream.reload:
      default: op
    stream.donation:
      default: op
    stream.admin:
      default: op